name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.5.0
        with:
          root: .
      - name: Check for essential files
        run: |
          test -f LICENSE.txt
          test -f README.md
